using NUnit.Framework;

namespace Mainwave.MimeTypes.Tests;

[TestFixture]
public class ApplicationTests
{
    [TestCase(MimeType.Application.AtomXml, "application/atom+xml")]
    [TestCase(MimeType.Application.AtomcatXml, "application/atomcat+xml")]
    [TestCase(MimeType.Application.Ecmascript, "application/ecmascript")]
    [TestCase(MimeType.Application.EpubZip, "application/epub+zip")]
    [TestCase(MimeType.Application.Gzip, "application/gzip")]
    [TestCase(MimeType.Application.JavaArchive, "application/java-archive")]
    [TestCase(MimeType.Application.Javascript, "application/javascript")]
    [TestCase(MimeType.Application.Json, "application/json")]
    [TestCase(MimeType.Application.LdJson, "application/ld+json")]
    [TestCase(MimeType.Application.Mp4, "application/mp4")]
    [TestCase(MimeType.Application.Msword, "application/msword")]
    [TestCase(MimeType.Application.OctetStream, "application/octet-stream")]
    [TestCase(MimeType.Application.Ogg, "application/ogg")]
    [TestCase(MimeType.Application.Pdf, "application/pdf")]
    [TestCase(MimeType.Application.Pkcs10, "application/pkcs10")]
    [TestCase(MimeType.Application.Pkcs7Mime, "application/pkcs7-mime")]
    [TestCase(MimeType.Application.Pkcs7Signature, "application/pkcs7-signature")]
    [TestCase(MimeType.Application.Pkcs8, "application/pkcs8")]
    [TestCase(MimeType.Application.Postscript, "application/postscript")]
    [TestCase(MimeType.Application.RdfXml, "application/rdf+xml")]
    [TestCase(MimeType.Application.RssXml, "application/rss+xml")]
    [TestCase(MimeType.Application.Rtf, "application/rtf")]
    [TestCase(MimeType.Application.SmilXml, "application/smil+xml")]
    [TestCase(MimeType.Application.VndAmazonEbook, "application/vnd.amazon.ebook")]
    [TestCase(MimeType.Application.VndAppleInstallerXml, "application/vnd.apple.installer+xml")]
    [TestCase(MimeType.Application.VndMozillaXulXml, "application/vnd.mozilla.xul+xml")]
    [TestCase(MimeType.Application.VndMsExcel, "application/vnd.ms-excel")]
    [TestCase(MimeType.Application.VndMsFontobject, "application/vnd.ms-fontobject")]
    [TestCase(MimeType.Application.VndMsPowerpoint, "application/vnd.ms-powerpoint")]
    [TestCase(MimeType.Application.VndOasisOpendocumentPresentation, "application/vnd.oasis.opendocument.presentation")]
    [TestCase(MimeType.Application.VndOasisOpendocumentSpreadsheet, "application/vnd.oasis.opendocument.spreadsheet")]
    [TestCase(MimeType.Application.VndOasisOpendocumentText, "application/vnd.oasis.opendocument.text")]
    [TestCase(MimeType.Application.VndOpenxmlformatsOfficedocumentPresentationmlPresentation, "application/vnd.openxmlformats-officedocument.presentationml.presentation")]
    [TestCase(MimeType.Application.VndOpenxmlformatsOfficedocumentSpreadsheetmlSheet, "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet")]
    [TestCase(MimeType.Application.VndOpenxmlformatsOfficedocumentWordprocessingmlDocument, "application/vnd.openxmlformats-officedocument.wordprocessingml.document")]
    [TestCase(MimeType.Application.VndRar, "application/vnd.rar")]
    [TestCase(MimeType.Application.VndVisio, "application/vnd.visio")]
    [TestCase(MimeType.Application.X7zCompressed, "application/x-7z-compressed")]
    [TestCase(MimeType.Application.XAbiword, "application/x-abiword")]
    [TestCase(MimeType.Application.XBzip, "application/x-bzip")]
    [TestCase(MimeType.Application.XBzip2, "application/x-bzip2")]
    [TestCase(MimeType.Application.XCdf, "application/x-cdf")]
    [TestCase(MimeType.Application.XCsh, "application/x-csh")]
    [TestCase(MimeType.Application.XFontOtf, "application/x-font-otf")]
    [TestCase(MimeType.Application.XFontTtf, "application/x-font-ttf")]
    [TestCase(MimeType.Application.XFontWoff, "application/x-font-woff")]
    [TestCase(MimeType.Application.XFreearc, "application/x-freearc")]
    [TestCase(MimeType.Application.XhtmlXml, "application/xhtml+xml")]
    [TestCase(MimeType.Application.XHttpdPhp, "application/x-httpd-php")]
    [TestCase(MimeType.Application.Xml, "application/xml")]
    [TestCase(MimeType.Application.XmlDtd, "application/xml-dtd")]
    [TestCase(MimeType.Application.XPkcs12, "application/x-pkcs12")]
    [TestCase(MimeType.Application.XSh, "application/x-sh")]
    [TestCase(MimeType.Application.XShockwaveFlash, "application/x-shockwave-flash")]
    [TestCase(MimeType.Application.XSilverlightApp, "application/x-silverlight-app")]
    [TestCase(MimeType.Application.XsltXml, "application/xslt+xml")]
    [TestCase(MimeType.Application.XTar, "application/x-tar")]
    [TestCase(MimeType.Application.XWwwFormUrlencoded, "application/x-www-form-urlencoded")]
    [TestCase(MimeType.Application.Zip, "application/zip")]
    public void AssertApplicationMimeTypeValue(string valueUnderTest, string expectedValue)
    {
        Assert.That(valueUnderTest, Is.EqualTo(expectedValue));
    }
}
