name: Build and test

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - master

jobs:
  build-and-test:

    runs-on: ubuntu-18.04

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 2.2.108

      - name: Build project
        run: dotnet build -c Release

      - name: Run unit tests
        run: dotnet test -c Release
