name: Build and test

on:
  push

jobs:
  build-and-test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 2.2.108

    - name: Build project (release)
      run: dotnet build -c Release

    - name: Run unit tests
      run: dotnet test -c Release
