name: Build and test branch
on:
  push:
    branches-ignore:
      - main
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  build-and-test-branch:
    name: Build and test branch
    uses: markwhitaker/shared-workflows/.github/workflows/dotnet-build-and-test.yml@main
